# C
function python_executable_path end
function python_library_path end
function python_library_handle end
function python_version end

# Core
function pynew end
function pyisnull end
function pycopy! end
function getptr end
function pydel! end
function unsafe_pynext end

function ispy end
function pyis end
function pyrepr end
function pyascii end
function pyhasattr end
function pygetattr end
function pysetattr end
function pydelattr end
function pyissubclass end
function pyisinstance end
function pyhash end
function pytruth end
function pynot end
function pylen end
function pyhasitem end
function pygetitem end
function pysetitem end
function pydelitem end
function pydir end
function pycall end
function pyeq end
function pyne end
function pyle end
function pylt end
function pyge end
function pygt end
function pycontains end
function pyin end
function pyneg end
function pypos end
function pyabs end
function pyinv end
function pyindex end
function pyadd end
function pysub end
function pymul end
function pymatmul end
function pyfloordiv end
function pytruediv end
function pymod end
function pydivmod end
function pylshift end
function pyrshift end
function pyand end
function pyxor end
function pyor end
function pyiadd end
function pyisub end
function pyimul end
function pyimatmul end
function pyifloordiv end
function pyitruediv end
function pyimod end
function pyilshift end
function pyirshift end
function pyiand end
function pyixor end
function pyior end
function pypow end
function pyipow end
function pyiter end
function pynext end
function pybool end
function pystr end
function pybytes end
function pyint end
function pyfloat end
function pycomplex end
function pytype end
function pyslice end
function pyrange end
function pytuple end
function pylist end
function pycollist end
function pyrowlist end
function pyset end
function pyfrozenset end
function pydict end
function pydate end
function pytime end
function pydatetime end
function pyfraction end
function pyeval end
function pyexec end
function pywith end
function pyimport end
function pyprint end
function pyhelp end
function pyall end
function pyany end
function pycallable end
function pycompile end


# Convert
function pyconvert end
function pyconvert_add_rule end
function pyconvert_return end
function pyconvert_unconverted end

# Compat
function event_loop_on end
function event_loop_off end
function fix_qt_plugin_path end
function pytable end
