name: Benchmark PR
on:
  pull_request:

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: MilesCranmer/AirspeedVelocity.jl@action-v1
        with:
          tune: "true"
          bench-on: ${{ github.event.pull_request.head.sha }}
